name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Lint, Test & Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 bandit

      - name: Lint with flake8
        run: flake8 .

      - name: Run tests (pytest)
        run: pytest -q

      - name: Run Bandit security scan
        run: bandit -r . -lll

      - name: Secret scan with Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --exit-code 1
